version: "3.8"

services:
  app_exemplo:
    build:
      context: .  # Aponta para a pasta onde está o Dockerfile
    container_name: app_exemplo_service
    environment:
      AWS_ACCESS_KEY_ID: fakeKey
      AWS_SECRET_ACCESS_KEY: fakeSecret
    volumes:
      - ./src:/app_exemplo/src  # Mapeia toda a pasta app_smart para dentro do container
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbSmart
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: {}
