service: app-exemplo

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

plugins:
  - serverless-offline

functions:
  - ${file(src/functions.yaml)}  
      
custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000  # Porta na qual o serverless-offline vai rodar dentro do contêiner